# Generated by Django 5.1.2 on 2025-02-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.login'),
            preserve_default=False,
        ),
    ]
