# Generated by Django 5.1.6 on 2025-02-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_user_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
