# Generated by Django 5.1.6 on 2025-02-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='created_at',
            new_name='date',
        ),
    ]
